const rooflinkService = require('./rooflinkService');
const db = require('../database/db');

/**
 * Automated Supplement Detection Service
 *
 * Analyzes jobs and photos to automatically detect when supplements are needed
 * and creates supplement line items based on predefined rules and AI analysis.
 */

class SupplementDetectionService {
  constructor() {
    this.detectionRules = {
      photoThreshold: 80,          // Auto-detect if 80+ photos
      priceThreshold: 50000,       // Auto-detect if estimate > $50k
      daysSinceInspection: 7,      // Auto-detect if inspection was > 7 days ago
      commonSupplementItems: [
        { description: 'Additional storm damage - ridge caps', category: 'storm', unit_price: 350 },
        { description: 'Additional storm damage - flashing', category: 'storm', unit_price: 450 },
        { description: 'Hidden water damage discovered', category: 'water', unit_price: 800 },
        { description: 'Additional decking replacement', category: 'decking', unit_price: 600 },
        { description: 'Code compliance upgrades', category: 'compliance', unit_price: 500 },
        { description: 'Unforeseen structural repairs', category: 'structural', unit_price: 1200 },
      ],
    };
  }

  /**
   * Analyze a job to determine if supplement is needed
   */
  async analyzeJobForSupplement(jobId) {
    try {
      console.log(`🔍 Analyzing job ${jobId} for supplement needs...`);

      // Get full job details
      const jobDetails = await rooflinkService.getFullJobDetails(jobId);

      if (!jobDetails || !jobDetails.job) {
        throw new Error('Job not found');
      }

      const job = jobDetails.job;
      const photoCount = job.photo_count || 0;
      const estimateTotal = job.estimate_total || 0;

      const analysis = {
        jobId,
        needsSupplement: false,
        confidence: 0,
        reasons: [],
        recommendedItems: [],
        autoGenerated: false,
      };

      // Rule 1: High photo count (80+ photos indicates complexity)
      if (photoCount >= this.detectionRules.photoThreshold) {
        analysis.needsSupplement = true;
        analysis.confidence += 40;
        analysis.reasons.push(`High photo count (${photoCount} photos) indicates complex scope`);

        // Recommend items based on photo count
        if (photoCount >= 100) {
          analysis.recommendedItems.push({
            ...this.detectionRules.commonSupplementItems[5], // Structural
            quantity: 1,
            total: 1200,
            reason: 'Very high photo count suggests extensive damage',
          });
        }
      }

      // Rule 2: High value job (more likely to have hidden items)
      if (estimateTotal >= this.detectionRules.priceThreshold) {
        analysis.needsSupplement = true;
        analysis.confidence += 20;
        analysis.reasons.push(`High value job ($${estimateTotal.toLocaleString()}) - likely to have additional scope`);
      }

      // Rule 3: Check for keywords in job notes
      if (jobDetails.notes && jobDetails.notes.length > 0) {
        const keywords = ['damage', 'additional', 'unforeseen', 'hidden', 'discovered', 'storm', 'leak', 'water'];
        const notesText = jobDetails.notes.map(n => n.content || '').join(' ').toLowerCase();

        const foundKeywords = keywords.filter(kw => notesText.includes(kw));
        if (foundKeywords.length > 0) {
          analysis.needsSupplement = true;
          analysis.confidence += 15 * foundKeywords.length;
          analysis.reasons.push(`Job notes mention: ${foundKeywords.join(', ')}`);

          // Recommend specific items based on keywords
          if (notesText.includes('storm')) {
            analysis.recommendedItems.push({
              ...this.detectionRules.commonSupplementItems[0],
              quantity: 1,
              total: 350,
              reason: 'Storm damage mentioned in notes',
            });
          }
          if (notesText.includes('water') || notesText.includes('leak')) {
            analysis.recommendedItems.push({
              ...this.detectionRules.commonSupplementItems[2],
              quantity: 1,
              total: 800,
              reason: 'Water damage mentioned in notes',
            });
          }
        }
      }

      // Rule 4: Job age (older jobs might need supplements)
      if (job.date_created) {
        const jobDate = new Date(job.date_created);
        const daysSince = Math.floor((Date.now() - jobDate.getTime()) / (1000 * 60 * 60 * 24));

        if (daysSince >= this.detectionRules.daysSinceInspection && !job.date_roof_completed) {
          analysis.confidence += 10;
          analysis.reasons.push(`Job is ${daysSince} days old - additional items may have been discovered`);
        }
      }

      // Rule 5: Check if already has supplements
      if (job.supplement_count && job.supplement_count > 0) {
        analysis.confidence -= 20;
        analysis.reasons.push(`Job already has ${job.supplement_count} supplement(s)`);
      }

      // Cap confidence at 100
      analysis.confidence = Math.min(100, Math.max(0, analysis.confidence));

      console.log(`✓ Analysis complete. Needs supplement: ${analysis.needsSupplement}, Confidence: ${analysis.confidence}%`);

      return analysis;
    } catch (error) {
      console.error('Error analyzing job for supplement:', error);
      throw error;
    }
  }

  /**
   * Auto-generate supplement line items for a job
   */
  async autoGenerateSupplementItems(jobId, estimateId, analysis) {
    try {
      console.log(`Auto-generating supplement items for job ${jobId}...`);

      if (!analysis.needsSupplement || analysis.recommendedItems.length === 0) {
        return { success: false, message: 'No recommended items to create' };
      }

      // Create bulk supplement items
      const itemsToCreate = analysis.recommendedItems.map(item => ({
        description: `[AUTO] ${item.description}`,
        quantity: item.quantity,
        unit_price: item.unit_price,
        total: item.total,
        category: item.category || 'auto-detected',
        notes: item.reason,
        approved: false,
        auto_generated: true,
      }));

      const result = await rooflinkService.createBulkSupplementalItems(estimateId, itemsToCreate);

      // Log the auto-generation
      await this.logDetection(jobId, estimateId, analysis, result);

      console.log(`✓ Auto-generated ${itemsToCreate.length} supplement items`);

      return {
        success: true,
        itemsCreated: itemsToCreate.length,
        items: result.items,
        analysis,
      };
    } catch (error) {
      console.error('Error auto-generating supplement items:', error);
      throw error;
    }
  }

  /**
   * Scan all jobs and detect supplements needed
   */
  async scanAllJobsForSupplements() {
    try {
      console.log('🔍 Starting automated supplement detection scan...');
      console.log('Fetching jobs needing supplements...');

      // Get jobs that might need supplements
      const jobsNeedingSupplements = await rooflinkService.getJobsNeedingSupplements();

      const results = {
        scannedCount: jobsNeedingSupplements.length,
        needsSupplementCount: 0,
        autoGeneratedCount: 0,
        analyses: [],
      };

      console.log(`Found ${jobsNeedingSupplements.length} jobs to analyze`);

      for (const job of jobsNeedingSupplements) {
        try {
          const analysis = await this.analyzeJobForSupplement(job.id);

          if (analysis.needsSupplement && analysis.confidence >= 60) {
            results.needsSupplementCount++;

            // Auto-generate if confidence is high enough
            if (analysis.confidence >= 75 && analysis.recommendedItems.length > 0 && job.estimate_id) {
              const generated = await this.autoGenerateSupplementItems(job.id, job.estimate_id, analysis);
              if (generated.success) {
                results.autoGeneratedCount++;
                analysis.autoGenerated = true;
              }
            }
          }

          results.analyses.push(analysis);
        } catch (error) {
          console.error(`Error analyzing job ${job.id}:`, error.message);
        }
      }

      console.log(`✓ Scan complete. Found ${results.needsSupplementCount} jobs needing supplements`);
      console.log(`✓ Auto-generated supplements for ${results.autoGeneratedCount} jobs`);

      return results;
    } catch (error) {
      console.error('Error scanning jobs for supplements:', error.message);
      // Re-throw with more context
      throw new Error(`Supplement detection scan failed: ${error.message}`);
    }
  }

  /**
   * Log detection event to database
   */
  async logDetection(jobId, estimateId, analysis, result) {
    return new Promise((resolve, reject) => {
      db.run(
        `INSERT INTO supplement_detections
         (job_id, estimate_id, confidence, reasons, items_created, auto_generated, created_at)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        [
          jobId,
          estimateId,
          analysis.confidence,
          JSON.stringify(analysis.reasons),
          result.items ? result.items.length : 0,
          analysis.autoGenerated ? 1 : 0,
          new Date().toISOString(),
        ],
        (err) => {
          if (err) reject(err);
          else resolve();
        }
      );
    });
  }

  /**
   * Get detection history
   */
  async getDetectionHistory(jobId = null) {
    return new Promise((resolve, reject) => {
      const sql = jobId
        ? 'SELECT * FROM supplement_detections WHERE job_id = ? ORDER BY created_at DESC'
        : 'SELECT * FROM supplement_detections ORDER BY created_at DESC LIMIT 100';

      const params = jobId ? [jobId] : [];

      db.all(sql, params, (err, rows) => {
        if (err) reject(err);
        else {
          const history = rows.map(row => ({
            ...row,
            reasons: JSON.parse(row.reasons || '[]'),
          }));
          resolve(history);
        }
      });
    });
  }

  /**
   * Schedule automated detection (cron-like)
   */
  startAutomatedDetection(intervalHours = 24) {
    console.log(`Starting automated supplement detection (every ${intervalHours} hours)...`);

    const intervalMs = intervalHours * 60 * 60 * 1000;

    // Run immediately on start (but don't crash if it fails)
    this.scanAllJobsForSupplements().catch((error) => {
      console.warn('⚠️  Initial automated detection scan failed (will retry):', error.message);
    });

    // Then run on interval
    setInterval(() => {
      this.scanAllJobsForSupplements().catch((error) => {
        console.warn('⚠️  Automated detection scan failed (will retry on next interval):', error.message);
      });
    }, intervalMs);

    console.log(`✓ Automated detection scheduler started successfully`);
  }
}

module.exports = new SupplementDetectionService();
